import { Project } from 'ts-morph';
import { LaunchDarklyFlag } from './client';

interface TemplateArgs {
  flags: LaunchDarklyFlag[];
  environments: string[];
  flagInterfaceName: string;
  envTypeName: string;
}

function createFlagType(flag: LaunchDarklyFlag): string {
  if (flag.kind === 'boolean') {
    return 'boolean';
  }

  return flag.variations
    .map((variation) => `{ name: '${variation.name}', value: unknown }`)
    .join(' | ');
}

const HEADER = `/**
 * Autogenerated by: https://www.npmjs.com/package/launchdarkly-typegen
 */`;

export function template({
  flags,
  environments,
  flagInterfaceName,
  envTypeName,
}: TemplateArgs): string {
  const project = new Project();
  const sourceFile = project.createSourceFile('generated.ts', '', {
    overwrite: true,
  });

  // Add the header comment
  sourceFile.insertStatements(0, `${HEADER}\n`);

  // Create the flag interface
  const flagInterface = sourceFile.addInterface({
    name: flagInterfaceName,
    isExported: true,
  });

  flags
    .sort((a, b) => a.key.localeCompare(b.key))
    .forEach((flag) => {
      const property = flagInterface.addProperty({
        name: `'${flag.key}'`,
        type: createFlagType(flag),
      });

      if (flag.description) {
        property.addJsDoc({
          description: flag.description,
        });
      }
    });

  // Create the AppFlag type alias
  sourceFile.addTypeAlias({
    name: 'AppFlag',
    type: `keyof ${flagInterfaceName}`,
    isExported: true,
  });

  // Create the environment type alias
  sourceFile.addTypeAlias({
    name: envTypeName,
    type: environments.map((env) => `'${env}'`).join(' | '),
    isExported: true,
  });

  return sourceFile.getFullText();
}
