import { describe, it, expect } from 'vitest';
import { template } from './template';
import { LaunchDarklyFlag } from './client';

describe('template', () => {
  it('generates a template with standard args', () => {
    const args = {
      flags: [
        {
          key: 'feature2',
          kind: 'boolean',
          name: 'Feature 2',
        } satisfies LaunchDarklyFlag,
        {
          key: 'feature1',
          kind: 'boolean',
          name: 'Feature 1',
        } satisfies LaunchDarklyFlag,
        {
          key: 'feature3 with spaces',
          kind: 'boolean',
          name: 'Feature 3',
        } satisfies LaunchDarklyFlag,
      ],
      environments: ['dev', 'prod'],
      flagInterfaceName: 'Flags',
      envTypeName: 'Environment',
    };
    const expectedOutput = `/**
 * Autogenerated by: https://www.npmjs.com/package/launchdarkly-typegen
 */
export interface Flags {
    'feature1': boolean;
    'feature2': boolean;
    'feature3 with spaces': boolean;
}

export type AppFlag = keyof Flags;
export type Environment = 'dev' | 'prod';
`;
    expect(template(args)).toBe(expectedOutput);
  });

  // Add more tests for different scenarios
});
